server.port: 4040
spring.cloud.stream:
    function:
        definition: Process , productConsumerService
    bindings:
        Process-in-0:
            destination: event-topic
        Process-out-0:
            destination: product-topic
        productConsumerService-in-0:
            destination: product-topic
    kafka:
        bindings:
            Process-in-0:
                consumer:
                    configuration:
                        value:
                            deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            Process-out-0:
                producer:
                    configuration:
                        value:
                            serializer: org.springframework.kafka.support.serializer.JsonDeserializer
            productConsumerService-in-0:
                consumer:
                    configuration:
                        value:
                            deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        binder:
            brokers:
                - localhoat:9092
